title: Settings
id: 8
icon: mdi:settings-outline
cards:
##Compact Header Config
  # - type: custom:compact-custom-header

  - type: custom:tracker-card

  - type: entities
    show_header_toggle: false
    title: Status
    entities:
      - sensor.potential_breaking_changes
