---
alias: nightlight_dim
trigger:
  platform: state
  entity_id: sensor.motion_his_side
  to: 'detected'
  platform: state
  entity_id: sensor.motion_her_side
  to: 'detected'
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: 'input_boolean.j_status_sleeping'
          state: 'on'
        - condition: state
          entity_id: 'input_boolean.m_status_sleeping'
          state: 'on'
    - condition: numeric_state
      entity_id: light.wled_bed
      value_template: '{{ state.attributes.brightness }}'
      below: 75
action:
- service: scene.turn_on
  entity_id: scene.nightlight_dim
