---
alias: 'Low Battery Notification'
trigger:
  platform: time
  at: '17:30:00'
condition:
  condition: template
  value_template: >
    {%- for zwave in states.zwave if zwave.attributes.battery_level is defined and zwave.attributes.battery_level | int < 30 -%}
      {%- if loop.index == 1 -%} {{ True }} {%- endif -%}
    {%- endfor -%}
action:
  service: notify.html5_push
  data_template:
    message: >
      {%- for zwave in states.zwave if zwave.attributes.battery_level is defined and zwave.attributes.battery_level | int < 30 -%}
        The {{zwave.attributes.friendly_name | replace('_', ' ') }} battery is at {{ zwave.attributes.battery_level }}%!{{'\n'}}
      {%- endfor -%}
