---
############NIGHTLIGHT FUNCTION############
alias: nightlight_bright
initial_state: True
trigger:
  platform: state
  entity_id: sensor.motion_his_side
  to: 'detected'
  platform: state
  entity_id: sensor.motion_her_side
  to: 'detected'
condition:
  condition: and
  conditions:
      condition: or
      conditions:
          condition: state
          entity_id: 'input_boolean.ib_j_status_sleeping'
          state: 'on'
          condition: state
          entity_id: 'input_boolean.ib_m_status_sleeping'
          state: 'on'
      condition: or
      conditions:
          condition: state
          entity_id: 'light.wled_bed'
          state: 'off'
action:
  service: scene.turn_on
  entity_id: scene.nightlight_bright