- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
    
- platform: 'bayesian'
  name: 'josh_home'
  prior: 0.50
  probability_threshold: 0.95
  observations:
      - entity_id: 'device_tracker.flamingotter_mqtt_josh'
        prob_given_true: 0.9
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'home'