homeassistant:
  name: Dashboard
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 1230
  unit_system: imperial
  time_zone: Europe/Berlin
  customize: !include customize.yaml

zone:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_long
  radius: 1000
  icon: mdi:worker

http:
  api_password: !secret http_password
  base_url: ha.flamingotter.com
  ip_ban_enabled: True
  login_attempts_threshold: 5
  
logger:
  default: warning

recorder:
  exclude:
    entities:
     - sensor.since_last_boot
     - automation.refresh_owntracks
     
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time__date      
      - sensor.date__time
      - sensor.time_utc
      - sensor.yr_symbol

influxdb:
  host: 10.0.10.10
  database: !secret influx_database
  username: !secret influx_username
  password: !secret influx_password
  default_measurement: state
  max_retries: 3
  include:
    entities:
       - sensor.bedroom_heatidx
       - sensor.bedroom_temp
       - sensor.bedroom_hum
       - sensor.test_lux
       - sensor.test_temp
       - sensor.test_hum
       - sensor.dark_sky_temperature
       - sensor.dark_sky_humidity

media_player:
  - platform: kodi
    host: 10.0.10.199
    name: Kodi Living Room
    username: kodi
    password: !secret kodi_living_room
    enable_websocket: true
  - platform: samsungtv
    name: Samsung Q7
    host: 10.0.10.245
    port: 8001
    mac: E4:7D:BD:A7:02:0A

device_tracker:
#  - platform: nmap_tracker
#    hosts:
#      - 10.0.10.0/24
#    home_interval: 5
#    consider_home: 180
#    interval_seconds: 15
  - platform: owntracks
    max_gps_accuracy: 100
  - platform: unifi
    host: 10.0.10.10
    port: 8443
    detection_time: 180
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    site_id: default
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

tts:
  - platform: google
    language: 'en-us'

history:
  include:
    domains:
      - switch
      - light
      - media_player
    entities:
      - device_tracker.flamingotter_mqtt_josh
      - device_tracker.flamingotter_mqtt_mj
      - input_select.home_status
      - input_select.josh_status
      - input_select.mj_status
      - sensor.test_temp
      - sensor.test_hum
      - sensor.test_lux

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

octoprint:
  host: !secret octo_ip
  api_key: !secret octo_api_key
  bed: true
  number_of_tools: 1


################
####INCLUDES####
################
sensor: !include_dir_merge_list sensors/
light: !include lights.yaml
switch: !include switches.yaml
group: !include groups.yaml
input_boolean: !include misc/input_boolean.yaml
input_select: !include misc/input_select.yaml
input_number: !include misc/input_number.yaml
scene: !include_dir_merge_list scenes/
automation: !include_dir_merge_list automation/
script: !include_dir_merge_list scripts/
notify: !include notify.yaml
cloud: !include cloud.yaml
shell_command: !include_dir_merge_list shell_commands/
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml



################
####ENABLES#####
################
map:
sun:
frontend:
config:
