---
# configuration.yaml
homeassistant:
  packages: !include_dir_named integrations

  allowlist_external_dirs:
    - "www/tmp/"
    - "www/tmp/snapshots/parlor"
    - "/media/snapshots"
    - "/media/maintenance"