homeassistant:
  # name: Dashboard
  # latitude: !secret home_lat
  # longitude: !secret home_long
  # elevation: 876
  # unit_system: imperial
  # time_zone: America/Chicago
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant

custom_updater:
#https://github.com/custom-components/custom_updater/wiki/Installation
  component_urls:
# Released build
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json

lovelace:
  mode: yaml

zone:
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 1000
    icon: mdi:worker

  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_long
    radius: 75
    icon: mdi:home-heart

http:
  #api_password: !secret http_password
  base_url: ha.flamingotter.com
  ip_ban_enabled: True
  login_attempts_threshold: 5

weblink:
  entities:
    - name: Control Panel
      url: https://ha.flamingotter.com/local/tileboard/index.html

logger:
  default: warning

recorder:
  exclude:
    entities:
     - sensor.since_last_boot
     - automation.refresh_owntracks

logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_date
      - sensor.date_time
      - sensor.time_utc
      - sensor.yr_symbol
      - sensor.internet_time

# influxdb:
  # host: 10.0.10.10
  # database: !secret influx_database
  # username: !secret influx_username
  # password: !secret influx_password
  # default_measurement: state
  # max_retries: 3
  # include:
    # entities:
       # - sensor.bedroom_heatidx
       # - sensor.bedroom_temp
       # - sensor.bedroom_hum
       # - sensor.test_lux
       # - sensor.test_temp
       # - sensor.test_hum
       # - sensor.dark_sky_temperature
       # - sensor.dark_sky_humidity

media_player:
  - platform: kodi
    host: 10.0.10.199
    name: Kodi Living Room
    username: kodi
    password: !secret kodi_living_room
    enable_websocket: true
  - platform: samsungtv
    name: Samsung Q7
    host: 10.0.10.245
    port: 8001
    #mac: E4:7D:BD:A7:02:0A

  # - platform: alexa
    # email: !secret amazon_username
    # password: !secret amazon_password
    # url: amazon.com
    # exclude_devices:
    # - "This Device"
    # - "Maryleigh's Alexa Apps"
    # - "Joshua's Alexa Apps"

alexa_media:
  accounts:
    - email: !secret amazon_username
      password: !secret amazon_password
      url: amazon.com
      exclude_devices:
        - "This Device"
        - "Maryleigh's Alexa Apps"
        - "Joshua's Alexa Apps"

person:

device_tracker:
  # - platform: owntracks
  #   max_gps_accuracy: 100
  - platform: unifi
    host: 10.0.10.223
    port: 8443
    detection_time: 180
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    site_id: 3q1vqa71
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-us'

history:
  include:
    domains:
      - switch
      - light
      - media_player
    entities:
      - device_tracker.flamingotter_mqtt_pix3j
      - device_tracker.mobile_pix3_m
      - input_select.home_status
      - input_select.josh_status
      - input_select.mj_status
      - sensor.test_temp
      - sensor.test_hum
      - sensor.test_lux

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

octoprint:
  host: !secret octo_ip
  api_key: !secret octo_api_key
  bed: true
  number_of_tools: 1


################
####INCLUDES####
################
automation: !include_dir_merge_list includes/automation/
binary_sensor: !include includes/binary_sensors.yaml
camera: !include includes/camera.yaml
cloud: !include includes/cloud.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
light: !include includes/lights.yaml
notify: !include includes/notify.yaml
scene: !include_dir_merge_list includes/scenes/
script: !include_dir_merge_list includes/scripts/
sensor: !include_dir_merge_list includes/sensors/
shell_command: !include_dir_merge_list includes/shell_commands/
switch: !include includes/switches.yaml
cover: !include includes/cover.yaml


################
####ENABLES#####
################
map:
sun:
frontend:
  themes: !include includes/themes.yaml
  javascript_version: latest
config:
system_health:
tplink:
