title: Kitchen Dashboard
# resources: !include lovelace/resources/resources.yaml
dashboards: !include lovelace/dashboards/dashboards.yaml
background: var(--background-image)
custom_header: !include lovelace/cards/custom_header.yaml
views:
  - !include lovelace/views/kit/00_kit_view.yaml
  - !include lovelace/views/kit/01_kit_sec_view.yaml
  - !include lovelace/views/kit/03_kit_weather_view.yaml
  - !include lovelace/views/kit/04_kit_3d_view.yaml
  - !include lovelace/views/kit/10_vacuum_view.yaml
#
#############################