title: Kitchen Dashboard
# resources: !include lovelace/resources/resources.yaml
dashboards: !include lovelace/dashboards/dashboards.yaml
background: var(--background-image)
custom_header: !include lovelace/cards/custom_header.yaml
views:
  - !include lovelace/views/kit/00_home_view.yaml
  - !include lovelace/views/kit/01_security_view.yaml
  - !include lovelace/views/alt1/02_parlor_view.yaml
  - !include lovelace/views/alt1/03_kitchen_view.yaml
  - !include lovelace/views/alt1/04_family_view.yaml
  - !include lovelace/views/alt1/05_mbr_view.yaml
  - !include lovelace/views/alt1/06_office_view.yaml
  - !include lovelace/views/alt1/07_garage_view.yaml
  - !include lovelace/views/alt1/08_weather_view.yaml
  - !include lovelace/views/alt1/09_settings_view.yaml
  #
  #
button_card_templates:
  label:
    styles:
      name:
        - font-size: 20px
        - justify-self: start
        - padding-left: 10px
  
  toggle:
    styles:
      card:
        - width: 100px
        - height: 75px
    tap_action:
      action: toggle
    hold_action: 
      action: more-info
  
  light:
    template: toggle
    state:
      - color: rgb(252, 220, 58)
        value: 'on'

  lock:
    template: toggle
    state:
      - color: green
        value: 'locked'
        styles:
          label:
            - color: green
      - color: red
        value: 'unlocked'
        styles:
          label:
            - color: red

  cover:
    template: toggle
    state:
      - color: green
        value: 'closed'
        styles:
          label:
            - color: green
      - color: red
        value: 'open'
        styles:
          label:
            - color: red

  boolean:
    styles:
      card:
        - width: 100px
        - height: 75px
    state:
      - value: 'off'
        styles:
          card:
            - filter: opacity(60%)
          icon:
            - filter: grayscale(100%)
    tap_action:
      action: none
    hold_action:
      action: toggle

  entity:
    styles:
      card:
        # - width: 100px
        - height: 75px
    tap_action:
      action: none

  home_state:
    template: entity
    state:
      - color: green
        value: 'Disarmed'
        styles:
          label:
            - color: green
      - color: red
        value: 'Armed'
        styles:
          label:
            - color: red
      - color: red
        value: 'Away'
        styles:
          label:
            - color: red
      - color: blue
        value: 'Sleeping'
        styles:
          label:
            - color: blue

  locks_state:
    template: entity
    state:
      - value: 'off'
        color: green
        styles:
          label:
            - color: green
      - color: red
        value: 'on'
        styles:
          label:
            - color: red
#
#
