- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "Motion Count His Side"
  value_template: '{{ value_json.moCnt }}'
- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "Motion Count Her Side"
  value_template: '{{ value_json.moCnt1 }}'


- platform: mqtt
  state_topic: "home/bedSensor1"
  name: "motion_count"
  value_template: '{{ value_json.moCnt }}'
- platform: mqtt
  state_topic: "home/bedSensor1"
  name: "ldr"
  value_template: '{{ value_json.ldr }}'


- platform: yr

- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "Motion His Side"
  value_template: '{{ value_json.mo }}'
- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "Motion Her Side"
  value_template: '{{ value_json.mo1 }}'

- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "longTrig His Side"
  value_template: '{{ value_json.lTrig }}'
- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "longTrig Her Side"
  value_template: '{{ value_json.lTrig1 }}'

- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "bedroom_temp"
  unit_of_measurement: '°F'
  device_class: 'temperature'
  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "flamingotter/bedSensor1"
  name: "bedroom_hum"
  unit_of_measurement: '%'
  value_template: '{{ value_json.hum }}'
- platform: mqtt
  state_topic: "flamingotter/bedSensor1/heatIdx"
  name: "bedroom_heatIdx"
  unit_of_measurement: '°F'
  #value_template: '{{ value_json.heatIdx }}'

- platform: mqtt
  state_topic: "home/basement/stairs"
  name: "Motion Basement Stairs"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "home/test"
  name: "Motion Test"
  value_template: '{{ value_json.motion }}'

- platform: darksky
  api_key: 7abceb2b826b08477b512a8bdc603787
  update_interval: '00:10'
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - icon
    - nearest_storm_distance
    - temperature
    - temperature_high
    - temperature_low
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - minutely_summary
    - hourly_summary
    - daily_summary
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase

- platform: template
  sensors:
    moonphases:
      entity_id: sensor.dark_sky_moon_phase
      friendly_name: 'Moon'
      value_template: '{{ states.sensor.dark_sky_moon_phase.state }}'
      entity_picture_template: >
        {% if states('sensor.dark_sky_moon_phase') | float == 0 %}
          /local/moons/0.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.04 %}
          /local/moons/2.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.08 %}
          /local/moons/3.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.12 %}
          /local/moons/4.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.16 %}
          /local/moons/5.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.20 %}
          /local/moons/6.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.25 %}
          /local/moons/7.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.28 %}
          /local/moons/8.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.32 %}
          /local/moons/9.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.36 %}
          /local/moons/10.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.40 %}
          /local/moons/11.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.44 %}
          /local/moons/12.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.50 %}
          /local/moons/13.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.52 %}
          /local/moons/14.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.56 %}
          /local/moons/15.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.60 %}
          /local/moons/16.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.64 %}
          /local/moons/17.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.68 %}
          /local/moons/18.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.72 %}
          /local/moons/19.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.75 %}
          /local/moons/20.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.80 %}
          /local/moons/21.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.84 %}
          /local/moons/22.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.88 %}
          /local/moons/23.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.92 %}
          /local/moons/24.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.96 %}
          /local/moons/25.png
        {% elif states('sensor.dark_sky_moon_phase') | float <= 0.99 %}
          /local/moons/26.png
        {% endif %}


- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'

- platform: api_streams

#- platform: speedtest
#  minute:
#    - 0
#    - 30
#  monitored_conditions:
#    - ping
#    - download
#    - uplo
