resources:
  - url: /local/custom-lovelace/card-modder.js
    type: js
  - url: /local/custom-lovelace/card-tools.js?
    type: js
  - url: /local/custom-lovelace/compact-custom-header.js?v=0.0.1
    type: module
  - url: /local/custom-lovelace/tracker-card.js?track=true
    type: module
  - url: /local/custom-lovelace/slider-entity-row.js
    type: js
  - url: /local/custom-lovelace/circle-sensor-card.js
    type: module
  - url: /local/custom-lovelace/tiles-card.js
    type: js
  - url: /local/custom-lovelace/simple-thermostat.js?v=1
    type: module
#
background: var(--background-image)

cch:
  # - !include lovelace/cch.yaml
  swipe: true
  swipe_amount: 40
  swipe_prevent_default: true
  active_tab_color: '#00a1ff'
  menu: show
  options: show
  voice: hide
  notifications: clock
  clock_format: '12'
  clock_date: true
  exceptions:
    - conditions:
        user: mj
      config:
        hide_tabs: '8'
    - conditions:
        user_agent: Mobile
      config:
        hide_tabs: '7'

title: Dashboard
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/01_security_view.yaml
  - !include lovelace/02_parlor_view.yaml
  - !include lovelace/03_kitchen_view.yaml
  - !include lovelace/04_family_view.yaml
  - !include lovelace/05_office_view.yaml
  - !include lovelace/06_mbr_view.yaml
  - !include lovelace/07_weather_view.yaml
  - !include lovelace/08_settings_view.yaml
  # - !include lovelace/09_mobile_home_view.yaml
