title: Dashboard
resources: !include_dir_list lovelace/resources
background: var(--background-image)
cch: !include lovelace/cards/compact_custom_header.yaml
views:
  - !include lovelace/views/00_home_view.yaml
  - !include lovelace/views/01_security_view.yaml
  - !include lovelace/views/02_parlor_view.yaml
  - !include lovelace/views/03_kitchen_view.yaml
  - !include lovelace/views/04_family_view.yaml
  - !include lovelace/views/05_mbr_view.yaml
  - !include lovelace/views/06_office_view.yaml
  - !include lovelace/views/07_weather_view.yaml
  - !include lovelace/views/08_settings_view.yaml
  # - !include lovelace/views/09_mobile_home_view.yaml
