resources:
  - url: /local/custom-lovelace/card-modder.js
    type: js
  - url: /local/custom-lovelace/card-tools.js?
    type: js
  - url: /local/custom-lovelace/compact-custom-header.js
    type: module
  - url: /local/custom-lovelace/tracker-card.js?track=true
    type: module
  - url: /local/custom-lovelace/slider-entity-row.js
    type: js
  - url: /local/custom-lovelace/circle-sensor-card.js
    type: module
  - url: /local/custom-lovelace/tiles-card.js
    type: js

background: var(--background-image)

title: Dashboard
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/01_security_view.yaml
  - !include lovelace/02_parlor_view.yaml
  - !include lovelace/03_kitchen_view.yaml
  - !include lovelace/04_family_view.yaml
  - !include lovelace/05_office_view.yaml
  - !include lovelace/06_mbr_view.yaml
  - !include lovelace/07_weather_view.yaml
  - !include lovelace/08_settings_view.yaml
  - !include lovelace/09_mobile_home_view.yaml
