title: Dashboard

views:
##Main Tab
  - title: Main
    icon: mdi:home
    cards:

      - type: glance
        title: Living Room
        show_state: false
        entities:
          - entity: group.living_room
            icon: mdi:lamp
            name: All
            tap_action: toggle
          - entity: group.living_room_lamps
            icon: mdi:lamp
            name: Lamps
            tap_action: toggle
          - entity: light.corner_lamp
            tap_action: toggle
          - entity: light.table_lamp
            tap_action: toggle
          - entity: light.spot_light
            tap_action: toggle
          - entity: switch.paper_lamp
            icon: mdi:floor-lamp
            tap_action: toggle

      - type: glance
        title: Kitchen
        show_state: false
        entities:
          - entity: group.kitchen
            icon: mdi:lamp
            name: All
            tap_action: toggle
          - entity: light.kitchen_light
            tap_action: toggle
          - entity: switch.cabinet_light
            icon: mdi:led-strip
            tap_action: toggle

      - type: picture-glance
        title: Office
        show_state: false
        camera_image: camera.octoprint
        entities:
          - entity: switch.desk_light
            icon: mdi:desk-lamp
            tap_action: toggle
          - entity: switch.office_light
            tap_action: toggle
          - entity: switch.office_fan
            icon: mdi:fan
            tap_action: toggle
          - entity: sensor.test_temp
          - entity: sensor.motion_test
            icon: mdi:run

      - type: entity-filter
        title: Device Trackers
        show_header_toggle: true
        entities:
          - device_tracker.ashlee_a5
          - device_tracker.basement_stair_node
          - device_tracker.bed_node_sensor
          - device_tracker.esp_4edc25
          - device_tracker.esp_4edf45
          - device_tracker.flamingotter_mqtt_josh
          - device_tracker.flamingotter_mqtt_mj
          - device_tracker.octopi
          - device_tracker.sonoff_test
          - device_tracker.testnode
        state_filter:
          - 'home'
        card:
          type: glance
          title: My Device Trackers



##Living Room Tab
  - title: Living Room
    icon: mdi:sofa
    cards:
      - type: glance
        title: Living Room
        show_state: false
        entities:
          - entity: group.living_room_lamps
            icon: mdi:lamp
            name: Lamps
            tap_action: toggle
          - entity: light.corner_lamp
            tap_action: toggle
          - entity: light.table_lamp
            tap_action: toggle
          - entity: light.spot_light
            tap_action: toggle
          - entity: switch.paper_lamp
            icon: mdi:floor-lamp
            tap_action: toggle

##Living Room Tab
  - title: Kitchen
    icon: mdi:silverware-fork-knife
    cards:
      - type: glance
        title: Kitchen
        show_state: false
        entities:
          - entity: group.kitchen
            icon: mdi:lamp
            name: All
            tap_action: toggle
          - entity: light.kitchen_light
            tap_action: toggle
          - entity: switch.cabinet_light
            icon: mdi:led-strip
            tap_action: toggle

##Offcie Tab
  - title: Office
    icon: mdi:desktop-tower-monitor
    cards:
      - type: picture-glance
        title: Office
        show_state: false
        camera_image: camera.octoprint
        entities:
          - entity: switch.desk_light
            icon: mdi:desk-lamp
            tap_action: toggle
          - entity: switch.office_light
            tap_action: toggle
          - entity: switch.office_fan
            icon: mdi:fan
            tap_action: toggle
          - entity: sensor.test_temp
          - entity: sensor.motion_test
            icon: mdi:run
      - type: sensor
        entity: sensor.test_temp
        name: Office Temp
        hours_to_show: 72


##Weather Tab
  - title: Weather
    icon: mdi:weather-lightning-rainy
    cards:

      - type: weather-forecast
        title: Weather
        #show_header_toggle: true
        entity: weather.dark_sky
