title: Home
# resources: !include lovelace/resources/resources.yaml
background: var(--background-image)
# custom_header: !include lovelace/cards/custom_header.yaml
views:
  - !include lovelace/views/main/00_home_view.yaml
  - !include lovelace/views/main/01_security_view.yaml
  - !include lovelace/views/main/02_mbr_view.yaml
  - !include lovelace/views/main/03_kitchen_view.yaml
  - !include lovelace/views/main/04_parlor_view.yaml
  - !include lovelace/views/main/05_family_view.yaml
  - !include lovelace/views/main/06_office_view.yaml
  - !include lovelace/views/main/07_garage_view.yaml
  - !include lovelace/views/main/08_storage_view.yaml
  # - !include lovelace/views/main/09_grow_view.yaml
  - !include lovelace/views/main/10_vacuum_view.yaml
  - !include lovelace/views/main/11_settings_view.yaml
  #
  #####################################