title: Dashboard
resources: !include lovelace/resources/resources.yaml
background: var(--background-image)
custom_header: !include lovelace/cards/custom_header.yaml
views:
  - !include lovelace/views/00_home_view.yaml
  - !include lovelace/views/01_security_view.yaml
  - !include lovelace/views/02_parlor_view.yaml
  - !include lovelace/views/03_kitchen_view.yaml
  - !include lovelace/views/04_family_view.yaml
  - !include lovelace/views/05_mbr_view.yaml
  - !include lovelace/views/06_office_view.yaml
  - !include lovelace/views/07_weather_view.yaml
  - !include lovelace/views/08_settings_view.yaml
  # - !include lovelace/views/09_mobile_home_view.yaml
  