resources:
  - url: /local/custom-lovelace/card-modder.js
    type: js
  - url: /local/custom-lovelace/card-tools.js?
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /local/custom-lovelace/tiles-card.js
    type: js
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module

background: var(--background-image)

cch:
  # - !include lovelace/cch.yaml
  swipe: true
  swipe_amount: 30
  swipe_prevent_default: true
  active_tab_color: '#00a1ff'
  menu: show
  options: clock
  voice: hide
  # notifications: clock
  clock_format: '12'
  clock_date: true
  exceptions:
    - conditions:
        user: mj
      config:
        hide_tabs: '7,8'
    - conditions:
        user_agent: Mobile
      config:
        hide_tabs: '7'

title: Dashboard
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/01_security_view.yaml
  - !include lovelace/02_parlor_view.yaml
  - !include lovelace/03_kitchen_view.yaml
  - !include lovelace/04_family_view.yaml
  - !include lovelace/05_mbr_view.yaml
  - !include lovelace/06_office_view.yaml
  - !include lovelace/07_weather_view.yaml
  - !include lovelace/08_settings_view.yaml
  # - !include lovelace/09_mobile_home_view.yaml
