sensor.jasco_products_26931_smart_motion_switch_alarm_level_2:
  ignored: true
  polling_intensity: 0
sensor.jasco_products_26931_smart_motion_switch_alarm_type_2:
  ignored: true
  polling_intensity: 0
sensor.jasco_products_26931_smart_motion_switch_burglar_2:
  ignored: true
  polling_intensity: 0
sensor.jasco_products_26931_smart_motion_switch_sourcenodeid_2:
  ignored: true
  polling_intensity: 0
switch.jasco_products_26931_smart_motion_switch_switch_2:
  ignored: true
  polling_intensity: 0
