---
media_dim:
  sequence:
    - service: light.turn_on
      data: 
        entitiy_id:
          - light.media_one
          - light.media_two
          - light.media_three
          - light.media_four
        brightness_pct: 15
        color_temp: 222
    - service: light.turn_on
      data: 
        entitiy_id:
          - light.spot_light
        brightness_pct: 30
        rgb_color: [0,128,128]