---
lockdown:
sequence:
  - service: lock.lock
    entity_id: group.all_locks
  - service: light.turn_off
    entity_id: group.lights
  - service: cover.close_cover
    entity_id: cover.shuttle_bay
  - delay:
      seconds: 10
  - service: notify.html5_push
    data_template:
      title: Lockdown Report
      message:  >
        {% if is_state('binary_sensor.door_locks', 'on') and is_state('cover.shuttle_bay', 'open') %}
          The
          {%- for entity_id in states.group.door_locks.attributes.entity_id if states(entity_id) == 'unlocked' -%}
            {%- if loop.first %} {% elif loop.last %}, and {% else %}, {% endif -%}{{ state_attr(entity_id, 'friendly_name') }}
          {%- endfor %} may be unlocked and the Shuttle Bay is open.
        {% elif is_state('binary_sensor.door_locks', 'on') %}
          The 
          {%- for entity_id in states.group.door_locks.attributes.entity_id if states(entity_id) == 'unlocked' -%}
            {%- if loop.first %} {% elif loop.last %}, and {% else %}, {% endif -%}{{ state_attr(entity_id, 'friendly_name') }}
          {%- endfor %} may be unlocked.

        {% elif is_state('cover.shuttle_bay', 'open')%}
          The Shuttle Bay is open.
        {% else %}
          All Secure
        {% endif %}
  - service: notify.alexa_media
    data_template:
      message:  >
        {% if is_state('binary_sensor.door_locks', 'on') and is_state('cover.shuttle_bay', 'open') %}
          The
          {%- for entity_id in states.group.door_locks.attributes.entity_id if states(entity_id) == 'unlocked' -%}
            {%- if loop.first %} {% elif loop.last %}, and {% else %}, {% endif -%}{{ state_attr(entity_id, 'friendly_name') }}
          {%- endfor %} may be unlocked and the Shuttle Bay is open.
        {% elif is_state('binary_sensor.door_locks', 'on') %}
          The 
          {%- for entity_id in states.group.door_locks.attributes.entity_id if states(entity_id) == 'unlocked' -%}
            {%- if loop.first %} {% elif loop.last %}, and {% else %}, {% endif -%}{{ state_attr(entity_id, 'friendly_name') }}
          {%- endfor %} may be unlocked.

        {% elif is_state('cover.shuttle_bay', 'open')%}
          The Shuttle Bay is open.
        {% else %}
          All Secure
        {% endif %}
