#################################################################
#                                                               #
#                     Packages/Date & Time                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  Date Time:
    control: hidden
    entities:
      - sensor.time
      - sensor.date
      - sensor.time_utc
      - sensor.date_time
      - sensor.time_date
      - sensor.internet_time
      - sensor.rocket_launch_time
      - sensor.beat

#################################################################
#                                                               #
#                     Logbook/History/Recorder                  #
#                                                               #
#################################################################

logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_date
      - sensor.date_time
      - sensor.time_utc
      - sensor.yr_symbol
      - sensor.internet_time
      
recorder:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_date
      - sensor.date_time
      - sensor.time_utc
      - sensor.yr_symbol
      - sensor.internet_time
      
history:
  exclude:
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_date
      - sensor.date_time
      - sensor.time_utc
      - sensor.yr_symbol
      - sensor.internet_time

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Workday              #
#                                                  #
####################################################
  ##Workday=on Weekend=off
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                 Sensor - Template                #
#                                                  #
####################################################


  - platform: template
    sensors:
      dayoftheweek:
        value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
        entity_id: sensor.time

####################################################
#                                                  #
#                Sensor - Time/Date                #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat

####################################################
#                                                  #
#               Sensor - World Clock               #
#                                                  #
####################################################

#   - platform: worldclock
#     time_zone: America/Chicago
#     name: Local Time

#   - platform: worldclock
#     time_zone: Europe/London
#     name: London Time
