#### Puppy Lights

- name: s_puppy_lights_on
  entities:
    light.table_lamp:
      brightness: 255
      color_temp: 222
      transition: 5
      state: on
    light.front_door_light:
      state: on
