---
alias: family_room_scene_select
trigger:
  - platform: state
    entity_id: input_select.basement_scene_select
action:
  - service: script.turn_on
    data_template:
      entity_id: script.{{trigger.to_state.state}}
