title: Settings
id: 9
icon: mdi:settings-outline
cards:

  - type: entities
    show_header_toggle: false
    title: Switches
    entities:
      - input_boolean.pet_presence
      - input_boolean.media_automations
      - input_boolean.house_guests
      - input_boolean.cleaning
      - input_boolean.sexy_time

  - type: entities
    show_header_toggle: false
    title: Garage
    entities:
      - light.garage_overhead_light

  - type: entities
    show_header_toggle: false
    title: Trash Schedule
    entities:
      - binary_sensor.trash_day
      - input_select.trash_pickup_day

  - type: entities
    show_header_toggle: false
    title: Status
    entities:
      - sensor.last_boot
