title: Settings
id: 9
icon: mdi:cog-outline
cards:

  - type: entities
    show_header_toggle: false
    title: Switches
    entities:
      - input_boolean.pet_presence
      - input_boolean.media_automations
      - input_boolean.house_guests
      - input_boolean.cleaning
      - input_boolean.sexy_time
      - input_boolean.alarm_arm_night
      - input_boolean.lockdown

  - type: entities
    show_header_toggle: false
    title: TEST
    entities:
      - input_boolean.test1
      - binary_sensor.test1
      - input_boolean.test2
      - binary_sensor.test2
      - input_boolean.test3
      - binary_sensor.test3
      - input_boolean.test4
      - binary_sensor.test4
      - binary_sensor.contact_back_door
      - input_select.josh_status
      - input_select.mj_status

  - type: entities
    show_header_toggle: false
    title: Deck Lights
    entities:
      - light.deck_lights
      - light.n_deck
      - light.s_deck

  - type: entities
    show_header_toggle: false
    title: Trash Schedule
    entities:
      - binary_sensor.trash_day
      - input_select.trash_pickup_day

  # - type: custom:auto-entities
  #   card:
  #     type: entities
  #   filter:
  #     include:
  #     - attributes:
  #           battery_level: "<=100"
  

  - type: entities
    show_header_toggle: false
    title: Status
    entities:
      - sensor.last_boot
      - sensor.hacs
      - sensor.current_version
      - binary_sensor.updater
      
  - type: custom:battery-state-card
    title: Battery Status
    sort_by_level: "asc"
    entities:
      - sensor.motion_basement_stairs_battery_level
      - sensor.motion_kitchen_battery_level
      - sensor.motion_parlor_battery_level
      - sensor.schlage_front_door_battery_level
      - sensor.schlage_back_door_battery_level
      - sensor.basement_sensor_battery_level
      
