swipe: 'true'
menu: show
options: show
voice: hide
notifications: clock
clock_format: '12'
clock_date: true
exceptions:
  - conditions:
      user: mj
    config:
      hide_tabs: '8'
  - conditions:
      user_agent: Mobile
    config:
      hide_tabs: '7'
