#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  # customize:
    
  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  sun:
    name: Sun
    view: no
    entities:
      - sun.sun
      - sensor.moon
      
  # weather overview:
    # name: Weather Overview
    # view: no
    # entities:
      # - sensor.pws_temp_c
      # - sensor.pws_relative_humidity
      # - sensor.pws_precip_1d
      # - sensor.pws_wind_kph
      # - sensor.pws_alerts
      
  # daily forcast:
    # name: Daily Forcast
    # view: no
    # entities:
      # - sensor.pws_temp_high_1d_c
      # - sensor.pws_temp_high_2d_c
      # - sensor.pws_temp_high_3d_c
      # - sensor.pws_temp_high_4d_c

#################################################################
#                                                               #
#                           Radar                               #
#                                                               #
#################################################################

# camera:
  # - platform: 'bom_radar'
    # name: "Bom Radar"
    # product_id: 'IDR663'
    
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  Sensor - Darksky                #
#                                                  #
####################################################
  
## Weather Dark Sky
  - platform: darksky
    api_key: !secret darksky_api
    scan_interval: '00:10'
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - icon
      - nearest_storm_distance
      - temperature
      - temperature_high
      - temperature_low
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - minutely_summary
      - hourly_summary
      - daily_summary
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_intensity_max
      - uv_index
      - moon_phase

####################################################
#                                                  #
#                   Sensor - Mold                  #
#                                                  #
####################################################

  # - platform: mold_indicator
    # name: Bathroom Mold Indicator
    # indoor_temp_sensor: sensor.temperature_158d00022c7248
    # indoor_humidity_sensor: sensor.humidity_158d00022c7248
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0
    
  # - platform: mold_indicator
    # name: Lounge Mold Indicator
    # indoor_temp_sensor: sensor.temperature_158d0001f558f5
    # indoor_humidity_sensor: sensor.humidity_158d0001f558f5
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0
    
  # - platform: mold_indicator
    # name: Playroom Mold Indicator
    # indoor_temp_sensor: sensor.temperature_158d0001f56682
    # indoor_humidity_sensor: sensor.humidity_158d0001f56682
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0
    
  # - platform: mold_indicator
    # name: Patio Mold Indicator
    # indoor_temp_sensor: sensor.bom_temp
    # indoor_humidity_sensor: sensor.humidity_158d0001f56350
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0
    
  # - platform: mold_indicator
    # name: Bedroom Mold Indicator
    # indoor_temp_sensor: sensor.temperature_158d0001f53de9
    # indoor_humidity_sensor: sensor.humidity_158d0001f53de9
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0
    
  # - platform: mold_indicator
    # name: Jackson Mold Indicator
    # indoor_temp_sensor: sensor.temperature_158d0001f534e1
    # indoor_humidity_sensor: sensor.humidity_158d0001f534e1
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0
    
  # - platform: mold_indicator
    # name: Hudson Mold Indicator
    # indoor_temp_sensor: sensor.temperature_158d0001f54df3
    # indoor_humidity_sensor: sensor.humidity_158d0001f54df3
    # outdoor_temp_sensor: sensor.temperature_158d0001f56350
    # calibration_factor: 2.0

####################################################
#                                                  #
#                   Sensor - Moon                  #
#                                                  #
####################################################

  - platform: moon
  
####################################################
#                                                  #
#                   Sensor - MQTT                  #
#                                                  #
####################################################

    
####################################################
#                                                  #
#                  Sensor - Season                 #
#                                                  #
####################################################

  - platform: season
    type: astronomical

####################################################
#                                                  #
#                 Sensor - Template                #
#                                                  #
####################################################
      
  # - platform: template
    # sensors:
      # bom_temp:
        # friendly_name: "Gold Coast Temperature"
        # value_template: "{{ states.weather.bom_gold_coast.attributes.temperature }}"
        # device_class: temperature
        # unit_of_measurement: °C
        
      # bom_humd:
        # friendly_name: "Gold Coast Humidity"
        # value_template: "{{ states.weather.bom_gold_coast.attributes.humidity }}"
        # #device_class: humidity
        # unit_of_measurement: '%'
        
      # bom_wind_sp:
        # friendly_name: "Gold Coast Wind Speed"
        # value_template: "{{ states.weather.bom_gold_coast.attributes.wind_speed }}"
        # #device_class: temperature
        # unit_of_measurement: km
        
      # bom_wind_bear:
        # friendly_name: "Gold Coast Wind Bearing"
        # value_template: "{{ states.weather.bom_gold_coast.attributes.wind_bearing }}"
        # #device_class: temperature
        # #unit_of_measurement: km
        
      # bom_pres:
        # friendly_name: "Gold Coast Pressure"
        # value_template: "{{ states.weather.bom_gold_coast.attributes.pressure }}"
        # #device_class: temperature
        # unit_of_measurement: hPa
        
      # aqi:
        # friendly_name: "Air Quality Index"
        # value_template: "{{ states.sensor.us_air_quality_index_2.state }}"
        
      # kc_temp:
        # friendly_name: "Kingia Castle Temperature"
        # value_template: "{{ states.sensor.temperature_158d0001f56350.state }}"
        
      # kc_temp_min:
        # value_template: "{{ states.sensor.stats_kc_temp_mean.attributes.min_value }}"
        # unit_of_measurement: '°C'
        
      # kc_temp_max:
        # value_template: "{{ states.sensor.stats_kc_temp_mean.attributes.max_value }}"
        # unit_of_measurement: '°C'
        
      # kc_humd:
        # friendly_name: "Kingia Castle Humidity"
        # value_template: "{{ states.sensor.humidity_158d0001f56350.state }}"
        
      # kc_humd_min:
        # value_template: "{{ states.sensor.stats_kc_humd_mean.attributes.min_value }}"
        # unit_of_measurement: '%'
        
      # kc_humd_max:
        # value_template: "{{ states.sensor.stats_kc_humd_mean.attributes.max_value }}"
        # unit_of_measurement: '%'
        
      # kc_wind:
        # value_template: "{{ states.weather.bom_gold_coast.attributes.wind_speed }}"
        
      # kc_wind_min:
        # value_template: "{{ states.sensor.stats_kc_wind_mean.attributes.min_value }}"
        # unit_of_measurement: 'km/h'
        
      # kc_wind_max:
        # value_template: "{{ states.sensor.stats_kc_wind_mean.attributes.max_value }}"
        # unit_of_measurement: 'km/h'
        
      # kc_wind_bearing:
        # value_template: "{{ states.weather.bom_gold_coast.attributes.wind_bearing }}"
        
      # kc_wind_dir:
        # friendly_name: 'Wind Direction'
        # value_template: >-
         # {% set wind_dir = states.sensor.kc_wind_bearing.state %}
         # {% if wind_dir | float<=11 %}N
         # {% elif wind_dir | float>348 %}N
         # {% elif 11 < (wind_dir|float) <=34 %}NNE
         # {% elif 34 < (wind_dir|float) <=56 %}NE
         # {% elif 56 < (wind_dir|float) <=79 %}}ENE
         # {% elif 79 < (wind_dir|float) <=101 %}E
         # {% elif 101 < (wind_dir|float) <=124 %}ESE
         # {% elif 124 < (wind_dir|float) <=146 %}SE
         # {% elif 146 < (wind_dir|float) <=169 %}SSE
         # {% elif 169 < (wind_dir|float) <=191 %}S
         # {% elif 191 < (wind_dir|float) <=214 %}SSW
         # {% elif 214 < (wind_dir|float) <=236 %}SW
         # {% elif 236 < (wind_dir|float) <=259 %}WSW
         # {% elif 259 < (wind_dir|float) <=281 %}W
         # {% elif 281 < (wind_dir|float) <=304 %}WWN
         # {% elif 304 < (wind_dir|float) <=326 %}NW
         # {% elif 326 < (wind_dir|float) <=348 %}NNW
         # {%- endif %}
         
      # spray_condition:
        # friendly_name: 'Spray Suitability'
        # value_template: >-
         # {% set suit = states.sensor.bom_gc_delta_temp_c.state %}
         # {% if suit | float<=2 %}Unsuitable
         # {% elif suit | float>2 %}Suitable
         # {% elif suit | float>8 %}Marginal
         # {% elif suit | float>10 %}Unsuitable
         # {%- endif %}
        # icon_template: >-
         # {% if is_state('sensor.spray_condition', 'Unsuitable') %}
            # mdi:hand
         # {% elif is_state('sensor.spray_condition', 'Suitable') %}
            # mdi:spray
         # {% elif is_state('sensor.spray_condition', 'Marginal') %}
            # mdi:sign-caution
         # {% endif %}
         
      # spray_condition_state:
        # friendly_name: 'Spray Suitability'
        # value_template: >-
         # {% set suit = states.sensor.bom_gc_delta_temp_c.state %}
         # {% if suit | float<=2 %}1
         # {% elif suit | float>2 %}3
         # {% elif suit | float>8 %}2
         # {% elif suit | float>10 %}1
         # {%- endif %}
        # icon_template: >-
         # {% if is_state('sensor.spray_condition', 'Unsuitable') %}
            # mdi:hand
         # {% elif is_state('sensor.spray_condition', 'Suitable') %}
            # mdi:spray
         # {% elif is_state('sensor.spray_condition', 'Marginal') %}
            # mdi:sign-caution
         # {% endif %}
        

#################################################################
#                                                               #
#                              Sun                              #
#                                                               #
#################################################################

sun:

#################################################################
#                                                               #
#                        Utility Meter                          #
#                                                               #
################################################################# 

# utility_meter:
  # rain_24h:
    # source: sensor.bom_gc_rain_today
    # cycle: daily
    
  # rain_7d:
    # source: sensor.bom_gc_rain_today
    # cycle: weekly
    
  # rain_m:
    # source: sensor.bom_gc_rain_today
    # cycle: monthly
    
  # rain_y:
    # source: sensor.bom_gc_rain_today
    # cycle: yearly
    
#################################################################
#                                                               #
#                            Weather                            #
#                                                               #
#################################################################

weather:

####################################################
#                                                  #
#                   Weather - BOM                  #
#                                                  #
####################################################

  # - platform: bom
    # station: IDQ60801.94592
    # name: Gold Coast
  
####################################################
#                                                  #
#                Weather - Darksky                 #
#                                                  #
####################################################
  
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
