############BED LED ANIMATION SPEED############
- id: bed_his_anination_speed
  alias: "His Bed Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
  - platform: state
    entity_id: input_number.bed_animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: "home/bedLed1/set"
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
