---
alias: 3dprinter_finished
initial_state: True
trigger:
  platform: state
  entity_id: sensor.octoprint_current_state
  from: 'Printing'
  to: 'Operational'
action:
- service: notify.html5_push_pixj
  data:
    title: '3D Print Complete'
    message: 'Print has been finished'
- service: notify.alexa_media
  data:
    data:
      type: announce
    target:
      - media_player.bedroom
      - media_player.family_room
      - media_player.kitchen
      - media_player.office
      - media_player.parlor
    message: 'Pardon the interuption, your 3D print has finished'