---
alias: 3dprinter_50_percent
trigger:
  platform: numeric_state
  entity_id: sensor.octoprint_job_percentage
  above: 50
action:
- service: notify.html5_push_pixj
  data:
    title: "50% done"
    message: "Print is at 50%"
- service: notify.alexa_media
  data:
    data:
      type: announce
    target:
      - media_player.bedroom
      - media_player.family_room
      - media_player.kitchen
      - media_player.office
      - media_player.parlor
    message: '3D print is half way finished'