---
alias: office_scene_select
trigger:
  - platform: state
    entity_id: input_select.office_scene_select
action:
  - service: scene.turn_on
    data_template:
      entity_id: scene.{{trigger.to_state.state}}
