#################################################################
#                                                               #
#                    Packages/Presence                          #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.josh_status:
      entity_picture: /local/josh.jpg
    sensor.mj_status:
      entity_picture: /local/mj.jpg


#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                           MQTT                                #
#                                                               #
#################################################################


#################################################################
#                                                               #
#                      Template Sensors                         #
#                                                               #
#################################################################

#sensor:
#  - platform: template
#    sensors:
#      josh_status:
#        friendly_name: "Josh Status"
#        value_template: >-
#          {% if is_state('input_select.josh_status', 'home') %}
#            Home
#          {% elif is_state('input_select.josh_status', 'just arrived') %}
#            Just Arrived
#          {% elif is_state('input_select.josh_status', 'just left') %}
#            Just Left
#          {% elif is_state('input_select.josh_status', 'away') %}
#            Away
#          {% elif is_state('input_select.josh_status', 'extended away') %}
#            Extended Away
#          {% if is_state('input_select.josh_status', 'work') %}
#            Work
#          {% endif %}
          
#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

### For Lovelace UI ###

####################################################
#                                                  #
#             Binary Sensor - Template             #
#                                                  #
####################################################


#################################################################
#                                                               #
#                       Input Selects                           #
#                                                               #
#################################################################

input_select:
  josh_status:
    name: Josh Status
    options:
    - "Work"
    - "Home"
    - "Just Arrived"
    - "Just Left"
    - "Away"
    - "Extended Away"
  
  mj_status:
    name: MJ Status
    options:
    - "Work"
    - "Home"
    - "Just Arrived"
    - "Just Left"
    - "Away"
    - "Extended Away"


#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

automation:
### JUST ARRIVED
  #- id: just_arrived
  - alias: Tag person just arrived
    initial_state: True
    trigger:
    - platform: state
      entity_id: person.josh
      from: not_home
      to: home
    - platform: state
      entity_id: person.mj
      from: not_home
      to: home
    action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'person.josh' %}
            input_select.josh_status
          {% else %}
            input_select.mj_status
          {% endif %}
        option: >
          {% if trigger.entity_id == 'person.josh' %}
            {% if states.input_select.josh_status.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.mj_status.state == 'Just Left' %}
            Home
            {% else %}
            Just Arrived
            {% endif %}
          {% endif %}
  #  - service: notify.josh
  #    data_template:
  #      title: Just Arrived NEW
  #      message:  >
  #        {% if states('input_select.josh_status') == 'Just Arrived'%}
  #          Josh's status is {{states.input_select.josh_status.state}} {{now().strftime('%H:%M-%d%b')}}
  #        {% else %}
  #          MJ's status is {{states.input_select.mj_status.state}} {{now().strftime('%H:%M-%d%b')}}
  #        {% endif %}

### HOME
  #- id: person_home
  - alias: Tag person home
    initial_state: True
    trigger:
    - platform: state
      entity_id: input_select.josh_status
      to: 'Just Arrived'
      for:
        minutes: 3
    - platform: state
      entity_id: input_select.mj_status
      to: 'Just Arrived'
      for:
        minutes: 3
    - platform: state
      entity_id: input_select.josh_status
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.mj_status
      from: 'Just Left'
      to: 'Just Arrived'
    action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.josh_status' %}
            input_select.josh_status
          {% else %}
            input_select.mj_status
          {% endif %}
        option: Home

### JUST LEFT  
  #- id: just_left
  - alias: Mark person as just left
    initial_state: True
    trigger:
    - platform: state
      entity_id: person.josh
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: person.mj
      from: 'home'
      to: 'not_home'
    action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'person.josh' %}
            input_select.josh_status
          {% else %}
            input_select.mj_status
          {% endif %}
        option: Just Left

### AWAY
  #- id: person_away
  - alias: Mark person as away
    initial_state: True
    trigger:
    - platform: state
      entity_id: input_select.josh_status
      to: 'Just Left'
      for:
        minutes: 3
    - platform: state
      entity_id: input_select.mj_status
      to: 'Just Left'
      for:
        minutes: 3
    action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.josh_status' %}
            input_select.josh_status
          {% else %}
            input_select.mj_status
          {% endif %}
        option: Away
    - service: notify.html5_push_pixj
      data_template:
        title: "Away"
        message:  >
          {% if states('input_select.josh_status') == 'Away'%}
            Josh is {{states.input_select.josh_status.state}} {{now().strftime('%H:%M %d-%b')}} via {{states.person.josh.attributes.source_type}}
          {% else %}
            MJ is {{states.input_select.mj_status.state}} {{now().strftime('%H:%M %d-%b')}} via {{states.person.josh.attributes.source_type}}
          {% endif %}
          
### EXTENDED AWAY          
  #- id: extended_away
  - alias: Mark person as extended away
    initial_state: True
    trigger:
    - platform: state
      entity_id: input_select.josh_status
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.mj_status
      to: 'Away'
      for:
        hours: 24
    action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.josh_status' %}
            input_select.josh_status
          {% else %}
            input_select.mj_status
          {% endif %}
        option: Extended Away
