---
trash_pickup_day:
  name: Current Trash Pickup Day (Evey Week)
  options:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    - Sunday
  icon: mdi:delete-variant