- platform: mqtt
  state_topic: "home/bedroomNode"
  name: "bedroom_temp"
  unit_of_measurement: '°F'
  device_class: 'temperature'
  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "home/bedroomNode"
  name: "bedroom_hum"
  unit_of_measurement: '%'
  value_template: '{{ value_json.hum }}'
