- platform: template
  sensors:
    sen_home_status:
      friendly_name: 'Home Status'
      entity_id: input_select.home_status
      value_template: >-
        {% if states.input_select.home_status.state == 'Disarmed' %}
          Disarmed
        {% elif states.input_select.home_status.state == 'Locked Down' %}
          Locked Down
        {% elif states.input_select.home_status.state == 'Away' %}
          Away
        {% elif states.input_select.home_status.state == 'Sleeping' %}
          Sleeping
        {% endif %}
      icon_template: >-
        {% if states.input_select.home_status.state == 'Disarmed' %}
          mdi:bell-off-outline
        {% elif states.input_select.home_status.state == 'Locked Down' %}
          mdi:bell-outline
        {% elif states.input_select.home_status.state == 'Away' %}
          mdi:airplane-takeoff
        {% elif states.input_select.home_status.state == 'Sleeping' %}
          mdi:weather-night
        {% endif %}
