- platform: template
  sensors:
    sen_home_status:
      friendly_name: 'Home Status'
      entity_id: input_boolean.ib_home_status_disarmed,
                 input_boolean.ib_home_status_locked_down,
                 input_boolean.ib_home_status_away, 
                 input_boolean.ib_home_status_sleeping
      value_template: >-
        {% if is_state('input_boolean.ib_home_status_disarmed', 'on') %}
          Disarmed
        {% elif is_state('input_boolean.ib_home_status_locked_down', 'on') %}
          Locked Down
        {% elif is_state('input_boolean.ib_home_status_away', 'on') %}
          Away
        {% elif is_state('input_boolean.ib_home_status_sleeping', 'on') %}
          Sleeping
        {% endif %}
      icon_template: >-
        {% if is_state('input_boolean.ib_home_status_disarmed', 'on') %}
          mdi:bell-off-outline
        {% elif is_state('input_boolean.ib_home_status_locked_down', 'on') %}
          mdi:bell-outline
        {% elif is_state('input_boolean.ib_home_status_away', 'on') %}
          mdi:airplane-takeoff
        {% elif is_state('input_boolean.ib_home_status_sleeping', 'on') %}
          mdi:weather-night
        {% endif %}