- platform: yr

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'

#- platform: api_streams

- platform: systemmonitor
  resources:
    - type: last_boot