---
alias: sunset_parlor_lamps
trigger:
  - platform: sun
    event: sunset
    offset: "-1:30:00"
condition:
  - condition: state
    entity_id: input_select.home_status
    state: "Disarmed"
action:
  - service: light.lifx_set_state
    data:
      entity_id:
        - light.piano_lamp
        - light.table_lamp
      power: true
      transition: 60
      brightness_pct: 100
      kelvin: 4500
