---
####Tag person as 'Work'
alias: person_work
trigger:
  - platform: state
    entity_id: person.josh
    to: 'Work'
    for: 
      minutes: 3
  - platform: state
    entity_id: person.mj
    to: 'Work'
    for: 
      minutes: 3
action:
  - service: input_select.select_option
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'person.josh' %}
          input_select.josh_status
        {% else %}
          input_select.mj_status
        {% endif %}
      option: Work
