---
binary_sensor:
  - name: "Trash Day"
    unique_id: trash_day_binary_sensor
    state: "{{ states('sensor.dayoftheweek') == states('input_select.trash_pickup_day') }}"
    icon: "{{ iif(this.state == 'on', 'mdi:delete', 'mdi:delete-empty') }}"