---
trigger:
  - platform: zwave_js.value_updated
    entity_id:
      - sensor.front_door_lock_battery_level
    command_class: 128
    property: level
sensor:
  - name: "sensor.front_door_lock_battery_level_last_updated"
    state: "{{now().strftime('%Y-%m-%d %H:%M:%S')}}"