---
sensor:
  - name: last_alexa
    state: >
      {{ expand('group.echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
    availability: >
      {{ expand('group.echos') | selectattr('attributes.last_called','eq',True) | first is defined }}