blueprint:
  name: Motion-activated Light (Advanced)
  description: Turn on a light when motion is detected, with conditions and custom actions.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    global_conditions:
      name: Global Conditions
      description: Conditions that must be met for any action to occur.
      selector:
        condition:
      default: []
    turn_on_conditions:
      name: Turn On Conditions
      description: Conditions that must be met to run the turn on action.
      selector:
        condition:
      default: []
    turn_on_action:
      name: Turn On Action
      description: The action to perform when turning on the lights. Overrides the default turn on.
      selector:
        action:
      default:
        - service: light.turn_on
          target: !input light_target
    turn_off_conditions:
      name: Turn Off Conditions
      description: Conditions that must be met to run the turn off action.
      selector:
        condition:
      default: []
    turn_off_action:
      name: Turn Off Action
      description: The action to perform when turning off the lights. Overrides the default turn off.
      selector:
        action:
      default:
        - service: light.turn_off
          target: !input light_target

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input motion_entity
    to: "off"
    for: !input no_motion_wait
    id: motion_off

condition: !input global_conditions

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: and
            conditions: !input turn_on_conditions
        sequence: !input turn_on_action
      - conditions:
          - condition: trigger
            id: motion_off
          - condition: and
            conditions: !input turn_off_conditions
        sequence: !input turn_off_action