#################################################################
#                                                               #
#                    Packages/Trash Recycle                     #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.trash_day:
      friendly_name: Is it Trash Day today?
      icon: mdi:delete-variant
    sensor.trash_pickup_day:
      friendly_name: Trash Pickup Day
      icon: mdi:calendar-today
      hidden: true
    group.trash_recycle:
      friendly_name: Trash & Recycle
      icon: mdi:recycle

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  trash schedule:
    name: Trash Schedule
    view: no
    entities:
      - sensor.trash_day
      - input_select.trash_reminders
      - sensor.trash_pickup_day
      - input_select.trash_pickup_day

#################################################################
#                                                               #
#                        User Inputs                            #
#                                                               #
#################################################################
##Input Selects

input_select:
  trash_pickup_day:
    name: Current Trash Pickup Day (Evey Week)
    options:
     - Monday
     - Tuesday
     - Wednesday
     - Thursday
     - Friday
     - Saturday
     - Sunday
    icon: mdi:delete-variant
  
  trash_reminders:
    name: Trash Reminder
    options:
     - Bins Taken Out
     - Remind Later
     - Reset Trash Reminders

##Input Booleans

input_boolean:
  trash_reminders:
    name: Trash Reminders
    initial: on
    icon: mdi:delete-variant

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                   Sensor - MQTT                  #
#                                                  #
####################################################

#   - platform: mqtt
#     state_topic: "/home/trashpickupday"
#     name: "Trash Pickup Day"
#     value_template: "{{ value }}"
#     qos: 1

####################################################
#                                                  #
#                 Sensor - Template                #
#                                                  #
####################################################



#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#             Binary Sensor - Template             #
#                                                  #
####################################################
  - platform: template
    sensors:
#       trash_day:
#         friendly_name: Trash Day?
#         value_template: >-
#           {{ states('sensor.dayoftheweek') == states('input_select.trash_pickup_day') }}

      trash_icon:
        friendly_name: Trash Icon
#         entity_id: binary_sensor.trash_day
        value_template: >-
          {{ states('sensor.dayoftheweek') == states('input_select.trash_pickup_day') }}
        icon_template: >-
          {% if is_state('binary_sensor.trash_icon', 'on') %}
            mdi:delete
          {% else %}
            mdi:delete-empty
          {% endif %}

      # recycle:
      #   friendly_name: Recycle
      #   entity_id: sensor.recycle_day
      #   value_template: "{{ is_state('sensor.recycle_day', 'yes') }}"
      #   icon_template: >-
      #     {% if is_state('sensor.recycle_day', 'yes') %}
      #       fas:recycle
      #     {% elif is_state('sensor.recycle_day', 'no') %}
      #       fas:recycle
      #     {% else %}
      #       mdi:alert
      #     {% endif %}
      #
      # green:
      #   friendly_name: Green
      #   entity_id: sensor.green_day
      #   value_template: "{{ is_state('sensor.green_day', 'yes') }}"
      #   icon_template: >-
      #     {% if is_state('sensor.green_day', 'yes') %}
      #       mdi:leaf
      #     {% elif is_state('sensor.green_day', 'no') %}
      #       mdi:leaf
      #     {% else %}
      #       mdi:alert
      #     {% endif %}

#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

## Some automations for this package have now been moved to Node-RED please see Node-Red Flows folder within this package for more infomation! ##

automation:

  - alias: Reset Trash Reminders
    initial_state: true
    hide_entity: true
    trigger:
      - platform: time
        at: '09:00:00'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.trash_reminders
      - service: input_select.select_option
        data_template:
          entity_id: input_select.trash_pickup_day
          option: "{{states.sensor.trash_pickup_day.state}}"
      # - service: input_select.select_option
      #   data_template:
      #     entity_id: input_select.recycle_pickup_day
      #     option: "{{states.sensor.recycle_pickup_day.state}}"
      # - service: input_select.select_option
      #   data_template:
      #     entity_id: input_select.recycle_pickup_week
      #     option: "{{states.sensor.recycle_pickup_week.state}}"
