#################################################################
#                                                               #
#                    Packages/Trash Recycle                     #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.trash_pickup_day:
      friendly_name: Trash Pickup Day
      icon: mdi:calendar-today
      hidden: true
    group.trash_recycle:
      friendly_name: Trash & Recycle
      icon: mdi:recycle

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  trash schedule:
    name: Trash Schedule
    icon: mdi:delete
    view: no
    control: hidden
    entities:
#       - input_select.trash_reminders
      - binary_sensor.trash_day
      - input_select.trash_pickup_day

#################################################################
#                                                               #
#                        User Inputs                            #
#                                                               #
#################################################################
##Input Selects

input_select:
  trash_pickup_day:
    name: Current Trash Pickup Day (Evey Week)
    options:
     - Monday
     - Tuesday
     - Wednesday
     - Thursday
     - Friday
     - Saturday
     - Sunday
    icon: mdi:delete-variant
  
  trash_reminders:
    name: Trash Reminder
    options:
     - Bins Taken Out
     - Remind Later
     - Reset Trash Reminders

##Input Booleans

input_boolean:
  trash_reminders:
    name: Trash Reminders
    initial: on
    icon: mdi:delete-variant

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                 Sensor - Template                #
#                                                  #
####################################################

  - platform: template
    sensors:
      trash_day:
        friendly_name: 'Trash Day'
        entity_id: binary_sensor.trash_day
        value_template: >-
          {% if is_state('binary_sensor.trash_day', 'on') %}
            Put to Curb
          {% elif is_state('binary_sensor.trash_day', 'off') %}
            Not Today
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.trash_day', 'on') %}
            mdi:delete
          {% elif is_state('binary_sensor.trash_day', 'off') %}
            mdi:delete-empty
          {% endif %}

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#             Binary Sensor - Template             #
#                                                  #
####################################################
  - platform: template
    sensors:

      trash_day:
        friendly_name: Trash Day
        value_template: >-
          {{ states('sensor.dayoftheweek') == states('input_select.trash_pickup_day') }}
        icon_template: >-
          {% if is_state('binary_sensor.trash_day', 'on') %}
            mdi:delete
          {% else %}
            mdi:delete-empty
          {% endif %}

#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

## Some automations for this package have now been moved to Node-RED please see Node-Red Flows folder within this package for more infomation! ##

automation:

  - alias: Trash Day Notify
    trigger:
    - platform: state
      entity_id: binary_sensor.trash_day
      to: "on"
    action:
    - service: notify.html5_push
      data:
        title: Trash and Recycling
        message: Put to the Curb
        data:
          tag: "trash-notify"
          actions:
          - action: "trash_done"
            title: "Done"
          - action: "trash_passon"
            title: "Ask Other"

  - alias: trash button done clicked
    trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: "trash_done"
        target: pixj
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: "trash_done"
        target: pix3m
    action:
    - service: notify.html5_push
      data_template:
        title: Trash and Recycling
        message:  >
          {% if trigger.event.data.target == 'pixj' %}
            Josh Completed
          {% else %}
            MJ Completed
          {% endif %}
        target: >
          {% if trigger.event.data.target == 'pixj' %}
            pix3m
          {% else %}
            pixj
          {% endif %}
        data:
          tag: "trash-notify"

  - alias: trash button passon clicked
    trigger:
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: "trash_passon"
        target: pixj
    - platform: event
      event_type: html5_notification.clicked
      event_data:
        action: "trash_passon"
        target: pix3m
    action:
    - service: notify.html5_push
      data_template:
        title: Trash and Recycling
        message:  > 
          {% if trigger.event.data.target == 'pixj' %}
            YOU'RE MY ONLY HOPE.
          {% else %}
            CAN YOU SAVE THE DAY?
          {% endif %}
        target: >
          {% if trigger.event.data.target == 'pixj' %}
            pix3m
          {% else %}
            pixj
          {% endif %}
        data:
          tag: "trash-notify"

#   - alias: Reset Trash Reminders
#     initial_state: true
#     hide_entity: true
#     trigger:
#       - platform: time
#         at: '09:00:00'
#     action:
#       - service: input_boolean.turn_on
#         entity_id: input_boolean.trash_reminders
#       - service: input_select.select_option
#         data_template:
#           entity_id: input_select.trash_pickup_day
#           option: "{{states.sensor.trash_pickup_day.state}}"
      # - service: input_select.select_option
      #   data_template:
      #     entity_id: input_select.recycle_pickup_day
      #     option: "{{states.sensor.recycle_pickup_day.state}}"
      # - service: input_select.select_option
      #   data_template:
      #     entity_id: input_select.recycle_pickup_week
      #     option: "{{states.sensor.recycle_pickup_week.state}}"
