<<<<<<< HEAD
---
alias: Lockdown
trigger:
  - platform: state
    entity_id: input_boolean.lockdown
    to: 'on'
action:
=======
---
alias: Lockdown
trigger:
  - platform: state
    entity_id: input_boolean.lockdown
    to: 'on'
action:
>>>>>>> 3c1f39570d35d0834fc0ca489b4ebbc4ad0c85b3
  - service: script.lockdown