---
####Set theme base on sun state####
alias: onair_theme
trigger:
  - platform: state
    entity_id: input_boolean.onair
    to: "on"
  - platform: state
    entity_id: input_boolean.onair
    to: "off"
action:
  - service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.input_boolean.onair.state == "on" %}
          red
        {% else %}
          clear
        {% endif %}
