<<<<<<< HEAD
---
####Set theme base on sun state####
alias: set_theme
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
action:
  - service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          clear
        {% else %}
          clear-dark-vibrant
        {% endif %}
=======
---
####Set theme base on sun state####
alias: set_theme
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
action:
  - service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          clear
        {% else %}
          clear-dark
        {% endif %}
>>>>>>> 3c1f39570d35d0834fc0ca489b4ebbc4ad0c85b3
