---
platform: template
  sensors:
    j_sleep_status:
      friendly_name: "Josh Sleep Status"
      entity_id: sensor.status_sleeping
      value_template: >-
        {{ is_state('input_boolean.j_status_sleeping', 'on')
            or is_state('input_boolean.j_status_sleeping', 'off') }}
      icon_template: >-
        {% if is_state('input_boolean.j_status_sleeping', 'on') %}
            mdi:sleep
        {% elif is_state('input_boolean.j_status_sleeping', 'off') %}
            mdi:sleep-off
          {% endif %}