- platform: mqtt
  state_topic: "home/test1"
  name: "motion_test"
  value_template: '{{ value_json.mo }}'

- platform: mqtt
  state_topic: "home/test1"
  name: "test_temp"
  unit_of_measurement: '°F'
  device_class: 'temperature'
  value_template: '{{ value_json.temp }}'

- platform: mqtt
  state_topic: "home/test1"
  name: "test_hum"
  unit_of_measurement: '%'
  value_template: '{{ value_json.hum }}'

- platform: mqtt
  state_topic: "home/test1"
  name: "test_lux"
  #unit_of_measurement: '%'
  value_template: '{{ value_json.ldr }}'
