---
alias: contact_back_door
trigger:
  - platform: state
    entity_id: binary_sensor.contact_back_door
    to: "on"
    for: "00:03:00"
action:
  - service: notify.all_devices
    data:
      message: "Back Door is Open!"
      title: "Door Open"
  - service: notify.alexa_media
    data:
      message: "The Back Door is Open!"
      data: 
        type: announce
      target: 
        - media_player.echo_show
        - media_player.kitchen_echo
        - media_player.parlor
        - maeia_player.bedroom
        - media_player.babe_cave
        - media_player.family_room
        - media_player.garage