###CONVERT SWITCHES TO LIGHT ENTITIES
- platform: switch
  name: Office Lamp
  entity_id: switch.office_lamp

- platform: switch
  name: Front Door Light
  entity_id: switch.front_door_light

- platform: switch
  name: Kitchen Light
  entity_id: switch.kitchen_light

- platform: switch
  name: Dining Room Light
  entity_id: switch.dining_light

###GROUP ENTITIES TO SINGLE ENTITY
- platform: group
  name: Media lights
  entities:
    - light.media_one
    - light.media_two
    - light.media_three
    - light.media_four

- platform: group
  name: Living Room Lamps
  entities:
    - light.piano_lamp
    - light.table_lamp

- platform: group
  name: Bedroom Lamps
  entities:
    - light.eugene
    - light.rapunzel

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_light
    - light.dining_room_light
